spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 00230904b
    username: root
    url: jdbc:mysql://localhost:3306/book_ecommerce_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false



